name: "PR Validate Project"
description: "Action to check PR title contains Management Number and contain required labels"
inputs:
  gh_token:
    description: "Github Token"
    required: true
  title_regex:
    description: "Title Regex"
    required: true
    default: ^\[(([A-Z][A-Z0-9]+-[0-9]+)|NOJIRA)\]
  required_labels:
    description: "Required Github Labels"
    required: true
    default: "feature,bug,documentation,chore"
  project_monitoring:
    description: "Required Management Project"
    required: true
    default: "Jira"
runs:
  using: "node16"
  main: "dist/main.js"
